[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sdypy-FRF"
version = "0.2.0"
authors = [{name = "Janko Slavič et al.", email = "janko.slavic@fs.uni-lj.si"}]
maintainers = [{name = "Janko Slavič et al.", email = "janko.slavic@fs.uni-lj.si"}]
license = {text = "MIT"}
description = "Frequency response function as used in structural dynamics."
readme = "README.rst"
keywords = ["Frequency response function", "MIMO", "SIMO/MISO", "SISO", "structural dynamics"]
requires-python = ">=3.10"
dependencies = ["pyFRF >= 1.0"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/sdypy/sdypy-FRF"
Documentation = "https://pyfrf.readthedocs.io/en/latest/index.html"
Source = "https://github.com/sdypy/sdypy-FRF"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-copybutton>=0.5.2",
]
dev = [
    "sdypy-FRF[docs]",
    "twine",
    "wheel",
    "pytest",
    "build",
    "flake8",
]

[tool.hatch.build.targets.wheel]
packages = ["sdypy"]

[tool.hatch.build.targets.sdist]
include = [
    "sdypy/",
    "tests/",
    "docs/",
    "README.rst",
    "License",
    "pyproject.toml",
    "readthedocs.yaml",
    "CONTRIBUTING.rst",
]
exclude = [
    "docs/_build/**",
    "docs/build/**",
]
